spring.application.name=Farmacia

spring.datasource.url=jdbc:mysql://localhost:3306/bd_DAW1
spring.datasource.username=root
spring.datasource.password=mysql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

application.security.jwt.secret-key=farmacia-daw2-cibertec-proyecto-secret-key-2024-segura
application.security.jwt.expiration=60